server:
   servlet:
     context-path: /spring_boot_jd_shop
   port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_jd_shop?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: yxm174276
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  redis:
    host: 127.0.0.1
    port: 6379
#logging:
#  level:
#     com.yxm.spring_boot_jd_shop : debug
#  config: classpath:log4j2.yaml # 指定log4j配置文件的位置